### ISSUE TITLE
POSTing and PATCHing /api/v1/loops - 'stack' is always returned as an empty array.

### ISSUE THREAD

**Issue by stephband** [sound-io/bugs#4]
For example, the object:

    {
        name: 'hello',
        sample_rate: 96000,
        stack: [{
            url: 'http://parpy/parp',
            offset: 0,
            duration: 1
        }]
    }

Comes back as:

    {
        uuid: 'xxxx-xxxx-xxxx-xxxx',
        name: 'hello',
        sample_rate: 96000,
        stack: []
    }

Is it doing something clever like checking to see if a file exists at url before storing it?

**Comment by mbi** [comment]
`order` is a required argument of stack elements. If you omit it, the Loop object will not be saved and you *should* get a `HTTP 400 BAD REQUEST` response.
